spring:
  application:
    name: Distinct
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres_db
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8080
